Feat/#24
cau-likelion-org/kiwi-client pull request #25
Opened 2023-12-22 08:56 UTC by cjy3458

## 📌 PR 내용
***
- 글 작성 페이지 퍼블리싱

## 📝 코드 요약
***
-'''/components/post/.tsx''' :
글 작성 => 마크다운 에디터 
글 보내기 => 마크다운 형식을 string으로 보내줌
제목 및 글 작성 후 완료 버튼 => 카테고리 선택 모달창 띄우기
카테고리 선택 후 확인 버튼 => 선택한 카테고리, 제목, 내용 보내기
툴바 이미지 삽입 => 기존 이미지 삽입 버튼은 마크다운 이미지 넣는 글을 만들어주는 것 밖에 안됌 
ex) ![](이미지 링크)  그래서 커스텀해서 파일을 업로드하면 백엔드에 전송해서 백엔드가 파일 링크를 만들어주면 그걸 자동으로 글 작성 칸에 삽입되도록 구현

## 💌 해결 이슈
***
- Resolved : #24

## 📸 스크린샷 (선택)
***
![image](https://github.com/cau-likelion-org/kiwi-client/assets/81355787/5682e00e-2daa-4865-8aa8-f44a90f2be51)

2023-12-22 14:44 UTC, d0422 requested changes
리뷰 남겼습니다!

2023-12-22 14:44 UTC, d0422 commented on next.config.js
> +});
혹시 어떤 작업을 하신건지 알 수 있을까요?

2023-12-22 14:44 UTC, d0422 commented on package.json
> +    "styled-components": "^6.1.1"
업데이트가 됐네요~

2023-12-22 14:44 UTC, d0422 commented on src/components/post/MD.tsx
> +});
코드스플리팅인가요,...?

2023-12-22 14:44 UTC, d0422 commented on src/components/post/MD.tsx
> +	const [class2, setClass2] = useState<IOption | null>(null);
class1, class2보다는
generation, category가 더 적절한 이름이 될 수 있을 것 같아요!

2023-12-22 14:44 UTC, d0422 commented on src/components/post/MD.tsx
> +				const file = fileInput.files[0];
const [file]=fileInput.files;
로 개선할 수 있을 것 같아요

2023-12-22 14:44 UTC, d0422 commented on src/components/post/Dropdown.tsx
> +};
DropDown에서 select를 두가지를 사용중인데요, 이 컴포넌트는 재사용하기 어려워보여요.
Dropdown을 재사용할 수 있게 만들고 map을통해 렌더링해보면 어떨까요?

2023-12-22 14:44 UTC, d0422 commented on src/components/post/QuillEditor.tsx
> +	// };
불필요한 코드를 주석으로 남기기보다는, 브랜치나 stash를 조금 더 활용해 보면 좋을 것 같아요!

2023-12-22 14:44 UTC, d0422 commented on src/components/post/Dropdown.tsx
> +];
IOption하나로 관리하기보다는
```typescript
type IGeneration{
    value:|'9기'|'10기'|'11기';
    label:|'9기'|'10기'|'11기';
}
```
이렇게 조금 더 세분화 하는게 어떨까요?

2023-12-22 17:03 UTC, cjy3458 commented on next.config.js
> +});
에디터 설치는 처음이라 레퍼런스들 찾아보면서 했는데, 에디터에 관련된 부분은 아니고 불필요한 import를 제거해주면서 성능을 향상시킨다길래 한 번 써봤습니다!(체감은 잘 안돼요)

2023-12-22 17:03 UTC, cjy3458 commented on package.json
> +    "styled-components": "^6.1.1"
공부해야겠네요

2023-12-22 17:13 UTC, cjy3458 commented on src/components/post/MD.tsx
> +});
클라이언트 사이드에서만 불러올 수 있도록 하는 코드인데, 비동기적으로 모듈을 불러와서 컴포넌트 렌더링이 느려지네요... 제거하겠습니다

2023-12-22 17:23 UTC, cjy3458 commented on src/components/post/MD.tsx
> +				const file = fileInput.files[0];
옹 배열디스트럭처링.... 정말 오랜만에 보네요 개선하겠습니다!

2023-12-22 19:36 UTC, cjy3458 commented on src/components/post/MD.tsx
> +				const file = fileInput.files[0];
웹 api인  FileList 객체를 반환하기 때문에 인덱스 접근은 가능하지만 배열 메서드는 못쓴다네요 ㅠ
const [file] = Array.from(fileInput.files); 이렇게 개선하는건 어떤가요?

2023-12-23 16:28 UTC, cjy3458 commented on src/components/post/QuillEditor.tsx
> +	// };
마크다운인지 모르고 아무 에디터나 설치해서 사용해보고 있었는데, 깜빡하고 삭제를 안했네용

2023-12-23 16:28 UTC, cjy3458 commented on src/components/post/Dropdown.tsx
> +];
유니언옵션 한 번도 안써봤는데 해보겠습니다!

2023-12-23 18:27 UTC, cjy3458 commented on src/components/post/Dropdown.tsx
> +};
들어가는 options를 props로 넘겨줘서 다른 곳에서 컴포넌트를 사용할 땐 options만 만들어서 넘겨주면 부를 수 있도록 코드 수정했습니다!

2023-12-23 18:40 UTC, cjy3458 commented on src/components/post/Dropdown.tsx
> +];
세분화 후 request.d.ts에 분리까지 완료했습니다

2023-12-25 06:18 UTC, merged